config/routes.rb
Rails.application.routes.draw do
  get 'posts/create'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :image_url , presence: :true
    validates :title , presence: :true
    validates :content , presence: :true

    before_save :update_content

    def update_content
        # censurar la palabra spoiler
        acum = ""
        array = self.content.split
        array.each do |palabra|
            acum += "#{palabra} " if palabra.upcase != "SPOILER"
        end
        self.content = acum
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all.order(id: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    # byebug
    @post = Post.create(
      title: params[:title],
      content: params[:content],
      image_url: params[:image_url]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<form action="<%= posts_create_path  %>" class="container" id="create_posts">
  <div class="form-group">
    <label for="title">Title</label>
    <input name="title" type="text" class="form-control" id="title" required>
  </div>
  <div class="form-group">
    <label for="content">Content</label>
    <input name="content" type="text" class="form-control" id="content">
  </div>
  <div class="form-group">
    <label for="image_url">Image_URL</label>
    <input name="image_url" type="url" class="form-control" id="image_url">
  </div>
  
  <button type="submit" class="btn btn-primary">Enviar</button>
</form>



<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Image_url</th>
      <th scope="col">Created_at</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
        <tr>
            <th scope="row"><%= post.id %></th>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td><img src="<%= post.image_url %>" alt="<%= post.image_url %>" width="60px"  height="60px"></td>
            <td><%= post.created_at %></td>
        </tr>
    <% end %>
   </tbody>
</table>

app/views/posts/create.html.erb
<% if @post.errors.any? %>
 <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being
    saved:</h2>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
 </div>
<% else %>
 <h1>Exito !!!! </h1>
 <%= link_to 'Home', root_path  %>
<% end %>